/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353534",
        "primary-container": "#ff9933",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#72de5c",
        "primary": "#ffc08d",
        "on-primary-fixed-variant": "#6d3a00",
        "outline": "#a38d7c",
        "primary-fixed-dim": "#ffb77a",
        "tertiary": "#cdcdcd",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#4c2700",
        "inverse-on-surface": "#313030",
        "surface-tint": "#ffb77a",
        "secondary-container": "#078200",
        "on-secondary-fixed-variant": "#035300",
        "background": "#131313",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#d9ffc9",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-container": "#434545",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface": "#131313",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-secondary": "#023a00",
        "on-surface-variant": "#dbc2b0",
        "outline-variant": "#554336",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#8f4e00",
        "tertiary-container": "#b1b2b2",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#012200",
        "on-primary-fixed": "#2e1500",
        "secondary-fixed": "#8dfc75",
        "surface-dim": "#131313",
        "on-tertiary": "#2f3131",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "primary-fixed": "#ffdcc2",
        "error-container": "#93000a",
        "on-primary-container": "#693800",
        "secondary": "#72de5c",
        "on-background": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "unit": "8px",
        "container-margin": "24px",
        "stack-lg": "32px",
        "gutter": "16px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
