// ─────────────────────────────────────────────────────────────────────────────
//  reelsData.js  —  Static travel reel data for the Instagram-style Reels feed
// ─────────────────────────────────────────────────────────────────────────────

export const REELS_DATA = [
  {
    id: 'reel-001',
    user: {
      username: 'aventura_vibes',
      displayName: 'Aventura Vibes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aventura&backgroundColor=b6e3f4',
      verified: true,
    },
    caption: 'Sunset at Santorini — where time stands still 🌅 #Greece #Travel #Santorini',
    location: 'Santorini, Greece',
    audio: 'Golden Hour — JVKE',
    likes: 248_300,
    comments: 3_420,
    shares: 12_800,
    bookmarks: 89_500,
    thumbnail: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=400&q=80',
    videoSrc: null,
    tags: ['#Greece', '#Santorini', '#Travel'],
    category: 'adventure',
  },
  {
    id: 'reel-002',
    user: {
      username: 'nomad.lens',
      displayName: 'Nomad Lens',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nomad&backgroundColor=ffdfba',
      verified: false,
    },
    caption: 'Lost in the streets of Marrakech 🏙️ The colours here are unreal! #Morocco #Culture',
    location: 'Marrakech, Morocco',
    audio: 'Desert Rose — Sting',
    likes: 173_900,
    comments: 2_180,
    shares: 7_300,
    bookmarks: 41_000,
    thumbnail: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=400&q=80',
    videoSrc: null,
    tags: ['#Morocco', '#Marrakech', '#Culture'],
    category: 'culture',
  },
  {
    id: 'reel-003',
    user: {
      username: 'wild_wanders',
      displayName: 'Wild Wanders',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wild&backgroundColor=c0f5a9',
      verified: true,
    },
    caption: 'Hiking through Patagonia is another level 🏔️⛰️ Cold, wild, and breathtaking! #Patagonia',
    location: 'Patagonia, Argentina',
    audio: 'On Top Of The World — Imagine Dragons',
    likes: 512_000,
    comments: 8_910,
    shares: 34_100,
    bookmarks: 204_000,
    thumbnail: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=400&q=80',
    videoSrc: null,
    tags: ['#Patagonia', '#Hiking', '#Adventure'],
    category: 'adventure',
  },
  {
    id: 'reel-004',
    user: {
      username: 'foodie_traveler',
      displayName: 'Foodie Traveler',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=foodie&backgroundColor=ffd3e8',
      verified: false,
    },
    caption: 'Street food tour in Bangkok 🍜🔥 This pad thai changed my life! #Thailand #Food',
    location: 'Bangkok, Thailand',
    audio: 'Happiness — Rex Orange County',
    likes: 389_200,
    comments: 5_670,
    shares: 21_400,
    bookmarks: 133_000,
    thumbnail: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&q=80',
    videoSrc: null,
    tags: ['#Thailand', '#Bangkok', '#Food'],
    category: 'food',
  },
  {
    id: 'reel-005',
    user: {
      username: 'ocean_drift',
      displayName: 'Ocean Drift',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ocean&backgroundColor=a9e5f5',
      verified: true,
    },
    caption: 'Crystal clear waters of the Maldives 🌊🐠 Paradise found! #Maldives #Ocean',
    location: 'Malé Atoll, Maldives',
    audio: 'Blue (Da Ba Dee) — Eiffel 65',
    likes: 894_100,
    comments: 14_320,
    shares: 63_000,
    bookmarks: 421_000,
    thumbnail: 'https://images.unsplash.com/photo-1578922846501-a8ee2b68e71c?w=400&q=80',
    videoSrc: null,
    tags: ['#Maldives', '#Ocean', '#Paradise'],
    category: 'beach',
  },
  {
    id: 'reel-006',
    user: {
      username: 'tokyo_nights',
      displayName: 'Tokyo Nights',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tokyo&backgroundColor=e8d5f5',
      verified: false,
    },
    caption: 'Neon lights & ramen nights in Shinjuku 🌃🍜 Tokyo you never disappoint! #Japan',
    location: 'Shinjuku, Tokyo',
    audio: 'Midnight City — M83',
    likes: 657_800,
    comments: 9_840,
    shares: 45_600,
    bookmarks: 287_000,
    thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80',
    videoSrc: null,
    tags: ['#Japan', '#Tokyo', '#Nightlife'],
    category: 'city',
  },
  {
    id: 'reel-007',
    user: {
      username: 'northern_lights',
      displayName: 'Northern Lights',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aurora&backgroundColor=d4f5ff',
      verified: true,
    },
    caption: 'Aurora Borealis in Iceland 🌌✨ I cried actual tears. This planet is unreal.',
    location: 'Reykjavik, Iceland',
    audio: 'Aurora — Björk',
    likes: 1_230_000,
    comments: 22_100,
    shares: 89_300,
    bookmarks: 634_000,
    thumbnail: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400&q=80',
    videoSrc: null,
    tags: ['#Iceland', '#NorthernLights', '#Aurora'],
    category: 'adventure',
  },
  {
    id: 'reel-008',
    user: {
      username: 'desert_nomad',
      displayName: 'Desert Nomad',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=desert&backgroundColor=ffeabf',
      verified: false,
    },
    caption: 'Sunrise over the Sahara 🏜️🌅 Sleeping under the stars is the ultimate reset.',
    location: 'Sahara Desert, Morocco',
    audio: 'Africa — Toto',
    likes: 445_600,
    comments: 7_230,
    shares: 28_900,
    bookmarks: 178_000,
    thumbnail: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=400&q=80',
    videoSrc: null,
    tags: ['#Sahara', '#Desert', '#Morocco'],
    category: 'adventure',
  },
];

export const CATEGORIES = [
  { id: 'all',       label: 'All',       icon: 'auto_awesome'    },
  { id: 'adventure', label: 'Adventure', icon: 'hiking'          },
  { id: 'beach',     label: 'Beach',     icon: 'beach_access'    },
  { id: 'city',      label: 'City',      icon: 'location_city'   },
  { id: 'culture',   label: 'Culture',   icon: 'museum'          },
  { id: 'food',      label: 'Food',      icon: 'restaurant'      },
];
